<?php


/**
 * Skeleton subclass for representing a row from the 'boot' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 11/18/11 22:53:54
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Boot extends BaseBoot {

} // Boot
