<?php


/**
 * Skeleton subclass for representing a row from the 'schiedsrichter' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Nov 23 22:42:52 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Schiedsrichter extends BaseSchiedsrichter {

} // Schiedsrichter
