<?php


/**
 * Skeleton subclass for performing query and update operations on the 'teilnehmer' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 11/18/11 22:53:55
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TeilnehmerPeer extends BaseTeilnehmerPeer {

} // TeilnehmerPeer
